sudo: required
language: ruby
rvm:
- 2.4.0
before_install: gem install bundler -v 1.13.7
script:
- bundle exec rake test
deploy:
  provider: rubygems
  api_key:
    secure: "rcQ8I4cBn+UpROxhBUsldKbpiiZ9QNUEep8fLGbmcU6QqN5NA2VrdW/DDzXrgXPPLoTDxRF32K2clIjT6WHYopVOvCeAA0+kNjACtGEV8DKL5VlBz0yWvLqM5L7y6ZhmiL/XUibmN7jcvqqI96h2QRr3qeO4a3XUlAIBqotjMopkqqBcHfq9+19p8CS3yS9Y85c1mM5EDcP7E/3Sa3umK7vvoMh+ulz1mic/CNKSnJOdhicqspvpPLUP0vOZ4Jlnn8I41clkBA0FcbOvEmEU2GNtMR8xDS9e0t+aVBAD92AiKYlHNzWp/84r3ZNjMURmltSLRHOQKYQhFdNJUNxZj9f44mPZcMIqD1kkKFkrdzjRzqpGxldrlUwgGkdiFev9d3x8XYMybDI3SmFDPNfa8d7DeW/AYIwkW6j7rdaFQQLzG4AZnoaW6FOmldePk0hPDT47wdpVy5nItH8ZQax8qJmDOX46IRr4fZ6piXiWZlSIfdwUtdBD47fmZS9xxi+mKTggZYiy+th3txqaXORJCCaaJVo5Yg1hbMN73+yKtLtzmsw/nKr1yVVX3KhYQkNix3ZskNhuOJ2aN2stnVsYKbL0Y924sVp7OrSyg5cWqXEXYcWGpXOKlaABa593QFGwQGl6wo7JiFO7giMQw0n6B4xkRv910BBXSVzafHk+jwk="
    on:
      tags: true
env:
  global:
    secure: "rcQ8I4cBn+UpROxhBUsldKbpiiZ9QNUEep8fLGbmcU6QqN5NA2VrdW/DDzXrgXPPLoTDxRF32K2clIjT6WHYopVOvCeAA0+kNjACtGEV8DKL5VlBz0yWvLqM5L7y6ZhmiL/XUibmN7jcvqqI96h2QRr3qeO4a3XUlAIBqotjMopkqqBcHfq9+19p8CS3yS9Y85c1mM5EDcP7E/3Sa3umK7vvoMh+ulz1mic/CNKSnJOdhicqspvpPLUP0vOZ4Jlnn8I41clkBA0FcbOvEmEU2GNtMR8xDS9e0t+aVBAD92AiKYlHNzWp/84r3ZNjMURmltSLRHOQKYQhFdNJUNxZj9f44mPZcMIqD1kkKFkrdzjRzqpGxldrlUwgGkdiFev9d3x8XYMybDI3SmFDPNfa8d7DeW/AYIwkW6j7rdaFQQLzG4AZnoaW6FOmldePk0hPDT47wdpVy5nItH8ZQax8qJmDOX46IRr4fZ6piXiWZlSIfdwUtdBD47fmZS9xxi+mKTggZYiy+th3txqaXORJCCaaJVo5Yg1hbMN73+yKtLtzmsw/nKr1yVVX3KhYQkNix3ZskNhuOJ2aN2stnVsYKbL0Y924sVp7OrSyg5cWqXEXYcWGpXOKlaABa593QFGwQGl6wo7JiFO7giMQw0n6B4xkRv910BBXSVzafHk+jwk="
